const products = [
  {
    id: 1,
    tag: "Sale",
    image: "images/product_01.png",
    name: "Bioderma",
    link: "shop-single.html",
    price: { original: 95.0, current: 55.0 },
  },
  {
    id: 2,
    image: "images/product_02.png",
    name: "Chanca Piedra",
    link: "shop-single.html",
    price: { current: 70.0 },
  },
  {
    id: 3,
    image: "images/product_03.png",
    name: "Umcka Cold Care",
    link: "shop-single.html",
    price: { current: 120.0 },
  },
  {
    id: 4,
    image: "images/product_04.png",
    name: "Cetyl Pure",
    link: "shop-single.html",
    price: { original: 45.0, current: 20.0 },
  },
  {
    id: 5,
    image: "images/product_05.png",
    name: "CLA Core",
    link: "shop-single.html",
    price: { current: 38.0 },
  },
  {
    id: 6,
    tag: "Sale",
    image: "images/product_06.png",
    name: "Poo Pourri",
    link: "shop-single.html",
    price: { original: 89.0, current: 38.0 },
  },
];
